added the new initial dialog by zacho
- runKeYmaera script now uses
  de.uka.ilkd.key.dl.gui.initialdialog.MainWithInitialDialog as Main
  class
- initial configuration is only done using this dialog

diff --git a/bin/runKeYmaera b/bin/runKeYmaera
--- a/bin/runKeYmaera
+++ b/bin/runKeYmaera
@@ -1,15 +1,60 @@
 #!/bin/sh
 
+resolve_symlink  ()
+{ 
+   TARGET=`ls -l $1| awk '/\ ->\ /{print $NF}'`
+
+   if [ -n "$TARGET" ] ; then
+      RESULT="$TARGET"
+      case "$RESULT" in
+         /*) break ;;				# absolute symlink
+         *)  RESULT=`dirname $0`/"$RESULT" ;;	# relative symlink
+      esac
+   else
+      RESULT=$1
+   fi
+
+   echo "$RESULT"
+}
+
+UNAME=`uname -s 2>/dev/null | tr '[:upper:]' '[:lower:]'`
+ARCH=`uname -pm 2>/dev/null | tr '[:upper:]' '[:lower:]' | tr ' ' '-'`
+
+if [ -z "$JAVA_HOME" ] ; then
+    JAVA=`which java`
+    if [ -z "$JAVA" ] ; then
+	echo "Cannot find JAVA. Please set your PATH or \$JAVA_HOME."
+	exit 1
+    fi
+else
+    if [ "$UNAME" = "darwin" ] ; then
+	JRE=$JAVA_HOME/Home
+	JAVA=$JRE/bin/java
+# other OS
+    else
+	JRE=$JAVA_HOME/jre
+	JAVA=$JRE/bin/java
+    fi
+fi
 echo "Using JDK installation from:      $JAVA_HOME"
 
+
+# For debugging reasons disable JIT (otherwise strace doesn't work)
 JAVA_OPTIONS=
+#JAVA_OPTIONS=-classic
+
+# Uncomment the following definition for remote debugging on port 1234
+#JAVA_OPTIONS='-DKeyDebugFlag=on -Xdebug -Xnoagent -Djava.compiler=NONE -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=1234'
 
 #
 # Now $KEY_HOME  
 #
 
 if [ -z "$KEY_HOME" ] ; then
-	export KEY_HOME=`pwd`
+   KEY_HOME=`resolve_symlink "$0"`	# resolve symlink name
+   KEY_HOME=`dirname $KEY_HOME`		# strip executable filename
+   KEY_HOME=`cd "$KEY_HOME";pwd`	# and now expand the path to full
+   KEY_HOME=`dirname $KEY_HOME`		# strip bin/ sirectory
 fi
 echo "Using KeY installation from:      $KEY_HOME"
 
@@ -25,7 +70,7 @@ fi
 # KeY CLASSPATH
 #
 
-key_ext_jars="antlr.jar antlr3.jar stringtemplate.jar jargs.jar recoderKey.jar dresden-ocl-demo.jar xerces.jar log4j.jar JLink/JLink.jar orbital-ext.jar orbital-core.jar"
+key_ext_jars="antlr.jar antlr3.jar stringtemplate.jar recoderKey.jar log4j.jar JLink/JLink.jar orbital-ext.jar orbital-core.jar"
 
 keyclasspath="$KEY_HOME/system/binary/"
 
@@ -41,6 +86,12 @@ for i in $key_ext_jars ; do
        keyclasspath="${keyclasspath}:$current_jar"
     fi
 done
+
+if [ x$ASPECTJRTPATH != x ]
+then
+  echo "Using AspectJ runtime from:       $ASPECTJRTPATH"
+  keyclasspath=$keyclasspath:$ASPECTJRTPATH
+fi
 
 #
 # KeY-specific command line options
@@ -71,6 +122,13 @@ while [ $# -ne 0 ]; do
     esac
 done	
 
+
+if [ ! -d "$HOME/.key" ]
+then
+mkdir "$HOME/.key"
+fi
+
+
 # Fallback for KeY-specific binaries
 PATH=${PATH}:$KEY_LIB
 export PATH
@@ -82,9 +140,11 @@ export PATH
 #-server \
 #-XX:CompileThreshold=1500 \
 
-exec java $JAVA_OPTIONS $keysysprops $hpfix \
--ea:de.uka.ilkd.key... -noverify -Xms64m -Xmx1024m \
+$JAVA $JAVA_OPTIONS $keysysprops \
+-ea:de.uka.ilkd.key... -Xms64m -Xmx1024m \
 -Dkey.home=$KEY_HOME \
+-Dkey.simplify.logdir=$KEY_SIMPLIFY_LOG_DIR \
+-Dkey.ics.logdir=$KEY_ICS_LOG_DIR \
 -Dsun.awt.exception.handler=de.uka.ilkd.key.gui.ExceptionalHandler \
 -Djava.library.path=$KEY_HOME/system/binary:/usr/lib \
--classpath $keyclasspath de.uka.ilkd.key.gui.Main $keyarg dL
+-classpath $keyclasspath de.uka.ilkd.key.dl.gui.initialdialog.MainWithInitialDialog $keyarg dL
